<?php

// ini_set('display_errors', 1);
// ini_set('display_startup_errors', 1);
// error_reporting(E_ALL);

require 'vendor/autoload.php';
require("../../components/db.php");
require("user-ip.php");
// require("mdoc-crm.php");

if ($_SERVER["REQUEST_METHOD"] !== "POST") {
    echo json_encode(["status" => 400, "msg" => "Invalid request"]);
    exit;
}

// print_r($_POST);
// die();
// Form data

$name = $_POST['name'];
$mobile = $_POST['mobile'];
$email = $_POST['email'];
$service = $_POST['service'];
$message = $_POST['message'];

// UTM Params 
$source = $_POST['utm_source'];
$campaignname = $_POST['utm_campaign_name'];
$campaignid = $_POST['utm_campaign_id'];
$campaigncity = $_POST['utm_campaign_city'];
$gclid = $_POST['gclid'];
$utm_term = $_POST['utm_term'];
$utm_medium = $_POST['utm_medium'];
$utm_adid = $_POST['utm_adid'];
$utm_device = $_POST['utm_device'];
$utm_matchtype = $_POST['utm_matchtype'];
$utm_location = $_POST['utm_location'];

$user_ip = getUserIP();

// Save data to database

$query = "INSERT INTO lead_info (name, email, mobile_no, service, message, source, campaignname, campaignid, campaigncity, gclid, utm_term, utm_medium, utm_adid, utm_device, utm_matchtype, utm_location, ip) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

$stmt = $conn->prepare($query);

if (!$stmt) {
    echo json_encode(["status" => 500, "error" => $conn->error]);
    exit;
}

$stmt->bind_param(
    "sssssssssssssssss",
    $name,
    $email,
    $mobile,
    $service,
    $message,
    $source,
    $campaignname,
    $campaignid,
    $campaigncity,
    $gclid,
    $utm_term,
    $utm_medium,
    $utm_adid,
    $utm_device,
    $utm_matchtype,
    $utm_location,
    $user_ip
);

if ($stmt->execute()) {

    $lead_id = $conn->insert_id;
    // echo json_encode(["status" => 200, "msg" => "Data save to DB successfully"]);
} else {
    echo json_encode([
        "status" => 500,
        "error" => $stmt->error
    ]);
}

$stmt->close();
$conn->close();

$utm_source = strtolower($source);

if ($utm_source == "Organic Leads") {
    $source_details = 'Landing Page - Organic';
} else if ($utm_source == "google") {
    $source_details = 'Regular Ad- Google';
} else if ($utm_source == "facebook") {
    $source_details = 'Regular Ad- Meta';
} else {
    $source_details = 'Landing Page - Organic';
}

if (
    isset($source) && !empty($source) &&

    isset($campaignname) && !empty($campaignname) &&

    isset($campaignid) && !empty($campaignid) &&

    isset($name) && isset($email) && isset($mobile) &&

    !empty($name) && !empty($mobile)
) {

    // MDOC CRM Calling Function

    // $response = addLeadToCRM($name, $mobile, $email, $source_details);

    // print_r($response);

    // exit();

    // Send mail to cilent

    $mail = new PHPMailer;
    $mail->isSMTP();
    $mail->Host = 'smtp.hostinger.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'support@digitaltokri.co.in';
    $mail->Password = 'L9w1];pA1s;';
    $mail->SMTPSecure = 'ssl';
    $mail->Port = 465;
    $mail->setFrom('support@digitaltokri.co.in', 'Cosmos Laundry');

    $mail->addBCC('supriya.w@digitaltokri.com');
    $mail->addBCC('pooja.s@digitaltokri.com');
    $mail->addBCC('pramila.j@digitaltokri.com');


    $mail->isHTML(true);

    $mail->Subject = 'Cosmos Laundry | Website Enquiry';

    $mail->Body    = '<h2>Enquiry Generated by</h2>

    			<p>Name : ' . $name . '</p>
    			<p>Email : ' . $email . '</p>
    			<p>Contact No. : ' . $mobile . '</p> 
                <p>Service : ' . $service . '</p>
                <p>Message : ' . $message . '</p>
    		    <p>Source : ' . $source . '</p>
    			<p>Sub Source : ' . $campaignname . '</p>
    			<p>Client IP : ' . $user_ip . '</p>';


    if ($mail->send()) {

        echo json_encode([
            "status" => 200,
            "lead_id" => $lead_id
        ]);

        // echo 200;
    } else {

        echo $mail->ErrorInfo;

        echo 5001;
    }
} else {

    echo 5004;
}
