<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require 'vendor/autoload.php';
require("db.php");
require("user-ip.php");
require("mdoc-crm.php");

if ($_SERVER["REQUEST_METHOD"] !== "POST") {
    echo json_encode(["status" => 400, "msg" => "Invalid request"]);
    exit;
}

// print_r($_POST);
// die();
// Form data
$name = $_POST['name'] ?? ' ';
$mobile = $_POST['mobile'] ?? ' ';
$email = $_POST['email'] ?? ' ';
$requirement = $_POST['requirement'] ?? ' ';
$project = $_POST['project'] ?? ' ';
$location = $_POST['location'] ?? ' ';
$message = $_POST['message'] ?? ' ';
$s_schedule = $_POST['s_schedule'] ?? ' '; 
$form_name = $_POST['form_name'] ?? ' '; 

// UTM Params
$source = $_POST['utm_source'] ?? ' ';
$campaignname = $_POST['utm_campaign_name'] ?? ' ';
$campaignid = $_POST['utm_campaign_id'] ?? ' ';
$campaigncity = $_POST['utm_campaign_city'] ?? ' ';
$gclid = $_POST['gclid'] ?? ' ';
$utm_term = $_POST['utm_term'] ?? ' ';
$utm_medium = $_POST['utm_medium'] ?? ' ';
$utm_adid = $_POST['utm_adid'] ?? ' ';
$utm_device = $_POST['utm_device'] ?? ' ';
$utm_matchtype = $_POST['utm_matchtype'] ?? ' ';
$utm_location = $_POST['utm_location'] ?? ' ';

$user_ip = getUserIP();

// Save data to database

$query = "INSERT INTO lead_info (name, email, mobile_no, project, requirement, s_date, source, capaignname, capaignid, capaigncity, gclid, utm_term, utm_medium, utm_adid, utm_device, utm_matchtype, utm_location, ip) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

$stmt = $conn->prepare($query);

if (!$stmt) {
    echo json_encode(["status" => 500, "error" => $conn->error]);
    exit;
}

$stmt->bind_param(
    "ssssssssssssssssss",
    $name,
    $email,
    $mobile,
    $project,
    $requirement,
    $s_schedule,
    $source,
    $campaignname,
    $campaignid,
    $campaigncity,
    $gclid,
    $utm_term,
    $utm_medium,
    $utm_adid,
    $utm_device,
    $utm_matchtype,
    $utm_location,
    $user_ip
);

if ($stmt->execute()) {

    $lead_id = $conn->insert_id;
    // echo json_encode(["status" => 200, "msg" => "Data save to DB successfully"]);
} else {
    echo json_encode([
        "status" => 500,
        "error" => $stmt->error
    ]);
}

$stmt->close();
$conn->close();

$utm_source = strtolower($source);

if ($utm_source == "Organic Leads") {
    $source_details = 'Landing Page - Organic';
} else if ($utm_source == "google") {
    $source_details = 'Regular Ad- Google';
} else if ($utm_source == "facebook") {
    $source_details = 'Regular Ad- Meta';
} else {
    $source_details = 'Landing Page - Organic';
}

if (
    isset($source) && !empty($source) &&

    isset($campaignname) && !empty($campaignname) &&

    isset($campaignid) && !empty($campaignid) &&

    isset($name) && isset($email) && isset($mobile) &&

    !empty($name) && !empty($mobile)
) {

    // MDOC CRM Calling Function

    if($form_name=="enquiry_form" || $form_name=="scheduleform" ){

        if($project=="Yojangandha"){
         $apikey = "2e5324c0-73aa-49b7-a8d7-da2987fdc2df";
        $response = sendDataToCRM($name, $mobile, $email,$requirement, $source_details, $apikey);
        }elseif($project=="Shrirang"){
         $apikey = "c416b079-2a08-4a1a-b3b0-9f64cc698c6e";
        $response = sendDataToCRM($name, $mobile, $email, $source_details, $apikey);

        }

       //print_r($response);
    } 

    // exit();

    // Send mail to cilent

    $mail = new PHPMailer;
    $mail->isSMTP();
    $mail->Host = 'smtp.hostinger.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'support@digitaltokri.co.in';
    $mail->Password = 'L9w1];pA1s;';
    $mail->SMTPSecure = 'ssl';
    $mail->Port = 465;
    $mail->setFrom('support@digitaltokri.co.in', 'Satyaprabhaa Enquiry');

    $mail->addAddress('sadhan.m@digitaltokri.com');
    //$mail->addBCC('iradigital15@gmail.com');
    $mail->addBCC('supriya.w@digitaltokri.com');
    $mail->addBCC('pooja.s@digitaltokri.com');
    $mail->addBCC('nida.s@digitaltokri.com');


    $mail->isHTML(true);

    $mail->Subject = 'Satyaprabhaa  | Landing Page Enquiry';

    $mail->Body    = '<h2>Enquiry Generated by</h2>

    			<p>Name : ' . $name . '</p>
    			<p>Email : ' . $email . '</p>
    			<p>Contact No. : ' . $mobile . '</p> 
                <p>Enquire About Project : ' . $requirement . '</p>
    		    <p>Source : ' . $source . '</p>
    			<p>Sub Source : ' . $campaignname . '</p>
    			<p>Client IP : ' . $user_ip . '</p>';





    if ($mail->send()) {

        echo json_encode([
            "status" => 200,
            "lead_id" => $lead_id
        ]);
s
        // echo 200;
    } else {

        echo $mail->ErrorInfo;

        echo 5001;
    }
} else {

    echo 5004;
}


// MDOC CRM function

